services:
  - type: web
    name: fmb-api
    env: python
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn -w 4 -b 0.0.0.0:$PORT api:app'
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11

  - type: worker
    name: fmb-tcp-server
    env: python
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'python grok_fmb_server_v6.py'
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
